import os
import subprocess
import shutil

PWD = os.getcwd()
BRANCH_NAME = 'main'
REMOTE_HOST = 'origin'
PROTO_PROJECT_URL = 'git@github.com:thgamejam/proto.git'
DEFAULT_GIT_URL = 'https://git.com/thjam/microservices.git'

project_name = '{{cookiecutter.project_name}}'
git_url = '{{cookiecutter.git_url}}'
push_remote = '{{cookiecutter.push_to_remote_after_creation}}'

print(f'构建目录: {PWD}')

subprocess.call(f'git init -b {BRANCH_NAME}', shell = True)
subprocess.call(f'git submodule add {PROTO_PROJECT_URL} proto', shell = True)

proto_dir = os.path.join(PWD, 'proto')
shutil.rmtree(path = proto_dir)
os.makedirs(proto_dir, exist_ok = True)
with open(os.path.join(proto_dir, '.gitignore'),'w',encoding='utf-8') as file:
    file.write('# Code generated by Cookiecutter template for Kratos. DO NOT EDIT.\n')
    file.write('# ignore all\n')
    file.write('*\n')
    file.write('!.gitignore\n')

if DEFAULT_GIT_URL != git_url:
    subprocess.call(f'git remote add {REMOTE_HOST} {git_url}', shell = True)
    subprocess.call(f'git add .', shell = True)
    subprocess.call(f'git commit -m "ci: Create project"', shell = True)
    if push_remote == 'yes' or push_remote == 'y':
        subprocess.call(f'git push {REMOTE_HOST} {BRANCH_NAME}', shell = True)
